train_set = [
    ("send money now", 1),
    ("hello friend", 0),
    ("you are a prince", 1),
    ("this is a test", 0),
    ("win money from prince", 1),
    ("just checking in", 0),
    ("urgent: your account needs attention", 1),
    ("meeting at noon", 0),
    ("claim your prize", 1),
    ("let's catch up", 0),
    ("spam or not spam", 1),
    ("this is not spam", 1),
    ("limited time offer", 1),
    ("how are you doing today", 0),
    ("exclusive deal just for you", 1),
    ("urgent: action required", 1),
    ("let's schedule a call", 0),
    ("congratulations, you won!", 1),
    ("your feedback is important", 0),
    ("don't miss out on this opportunity", 1),
    ("we value your opinion", 0),
    ("urgent: update your information", 1),
    ("hello, how can I help you?", 0),
    ("this is a friendly reminder", 0),
    ("you have a new message", 0),
    ("important: please read carefully", 1),
    ("thank you for your support", 0),
    ("urgent: security alert", 1),
    ("let's collaborate on this project", 0),
    ("your subscription is expiring soon", 1),
    ("we appreciate your business", 0),
    ("urgent: payment required", 1),
    ("let's discuss your options", 0),
    ("you have a new notification", 0),
    ("important: changes to your account", 1),
    ("thank you for being a loyal customer", 0),
    ("urgent: verify your identity", 1),
    ("let's set up a meeting", 0),
    ("you have a new task assigned", 0),
    ("important: update your preferences", 1),
    ("we're here to assist you", 0),
    ("urgent: your attention is needed", 1),
    ("let's review your account", 0),
    ("you have a new alert", 0),
    ("important: action required on your part", 1),
    ("thank you for your feedback", 0),
    ("urgent: please respond immediately", 1),
    ("let's finalize the details", 0),
    ("you have a new update", 0),
    ("important: please take action", 1),
    ("we value your input", 0),
    ("urgent: your response is needed", 1),
    ("let's connect soon", 0),
    ("you have a new assignment", 0),
    ("important: please review", 1),
    ("thank you for your cooperation", 0),
    ("urgent: please take note", 1),
    ("let's discuss further", 0),
    ("you have a new reminder", 0),
    ("important: please acknowledge", 1),
    ("we appreciate your feedback", 0),
    ("urgent: please take action", 1),
    ("let's arrange a time to talk", 0),
    ("you have a new message waiting", 0),
    ("important: please check your account", 1),
    ("thank you for your understanding", 0),
    ("urgent: please address this issue", 1),
    ("let's work together on this", 0),
    ("you have a new notification alert", 0),
    ("important: please update your records", 1),
    ("we're here to help you", 0),
    ("urgent: your input is required", 1),
    ("let's schedule a follow-up", 0),
    ("you have a new task to complete", 0),
    ("important: please take note of this", 1),
    ("thank you for your prompt response", 0),
    ("urgent: please review this matter", 1),
    ("let's finalize the arrangements", 0),
    ("you have a new update available", 0),
    ("important: please take action now", 1),
    ("we value your business relationship", 0),
    ("urgent: your attention is crucial", 1),
    ("let's discuss your concerns", 0),
    ("you have a new assignment due", 0),
    ("important: please read this carefully", 1),
    ("thank you for your continued support", 0),
    ("urgent: please respond at your earliest convenience", 1),
    ("let's set up a time to meet", 0),
    ("you have a new task assigned to you", 0),
    ("important: please review the details", 1),
    ("we appreciate your prompt attention", 0),
    ("urgent: please take immediate action", 1),
    ("let's connect to discuss further", 0),
    ("you have a new reminder set", 0),
    ("important: please acknowledge receipt of this message", 1),
    ("thank you for your prompt attention to this matter", 0),
    ("urgent: please address this request", 1),
    ("let's work together to resolve this", 0),
    ("you have a new notification alert set", 0),
    ("important: please update your information promptly", 1),
    ("win a free iPhone by clicking here!", 1),
    ("let's meet up for coffee tomorrow.", 0),
    ("earn $5000 from home — no experience needed!", 1),
    ("can you send me the report later today?", 0),
    ("act now! Limited offer expires soon.", 1),
    ("i'll be home by 6pm tonight.", 0),
    ("congratulations! You won a prize.", 1),
    ("don't forget your dentist appointment.", 0),
    ("you are selected for a free vacation.", 1),
    ("meeting is rescheduled to Thursday.", 0),
    ("hot singles in your area want to chat.", 1),
    ("i'll bring snacks for the movie night.", 0),
    ("get rich quick with this one secret.", 1),
    ("let's catch up soon — been a while!", 0),
    ("exclusive deal just for you! Click now.", 1),
    ("thanks again for helping me move.", 0),
    ("make money fast with this trick!", 1),
    ("happy birthday! Hope it's a great one.", 0),
    ("this is your last chance to win big!", 1),
    ("dinner was awesome last night.", 0),
    ("limited-time crypto offer — invest now!", 1),
    ("do you want to go hiking Saturday?", 0),
    ("free gift for you, open now!", 1),
    ("be sure to save your work often.", 0),
    ("click here to verify your account.", 1),
    ("your Amazon order has been shipped.", 0),
    ("low interest loan waiting for approval!", 1),
    ("let's schedule a call this weekend.", 0),
    ("claim your $1000 gift card now!", 1),
    ("what did you think of the movie?", 0),
    ("URGENT: Your package needs confirmation.", 1),
    ("i'm heading out now — see you soon.", 0),
    ("earn rewards for simple tasks online!", 1),
    ("weather looks great for the weekend.", 0),
    ("you've been pre-approved. Click here.", 1),
    ("remember to bring your ID.", 0),
    ("get a loan with no credit check!", 1),
    ("the groceries are in the fridge.", 0),
    ("free trial ends soon. Act now!", 1),
    ("Want to go grab lunch later?", 0),
    ("double your income in 3 weeks!", 1),
    ("let's work on the project tomorrow.", 0),
    ("start earning from surveys today!", 1),
    ("don’t forget to email your professor.", 0),
    ("fastest way to burn belly fat!", 1),
    ("i'm free after 4pm today.", 0),
    ("this method made me rich overnight.", 1),
    ("where should we meet later?", 0),
    ("unlock exclusive deals now!", 1),
    ("i'll take the dog out this morning.", 0)
]

test_set = [
    ("urgent: your account needs attention", 1),
    ("hello friend", 0),
    ("you are a prince", 1),
    ("this is a test", 0),
    ("win money from prince", 1),
    ("just checking in", 0),
    ("meeting at noon", 0),
    ("claim your prize", 1),
    ("let's catch up", 0),
    ("spam or not spam", 1),
    ("this is not spam", 1),
    ("limited time offer", 1),
    ("how are you doing today", 0),
    ("exclusive deal just for you", 1),
    ("urgent: action required", 1),
    ("let's schedule a call", 0),
    ("congratulations, you won!", 1),
    ("your feedback is important", 0),
    ("don't miss out on this opportunity", 1),
    ("we value your opinion", 0),
    ("urgent: update your information", 1),
    ("hello, how can I help you?", 0),
    ("this is a friendly reminder", 0),
    ("you have a new message", 0),
    ("important: please read carefully", 1),
    ("thank you for your support", 0),
    ("urgent: security alert", 1),
    ("let's collaborate on this project", 0),
    ("your subscription is expiring soon", 1),
    ("we appreciate your business", 0),
    ("urgent: payment required", 1),
    ("let's discuss your options", 0),
    ("you have a new notification", 0),
    ("important: changes to your account", 1),
    ("thank you for being a loyal customer", 0),
    ("urgent: verify your identity", 1),
    ("let's set up a meeting", 0),
    ("you have a new task assigned", 0),
    ("important: update your preferences", 1),
    ("we're here to assist you", 0),
    ("urgent: your attention is needed", 1),
    ("let's review your account", 0),
    ("you have a new alert", 0),
    ("important: action required on your part", 1),
    ("thank you for your feedback", 0),
    ("urgent: please respond immediately", 1),
    ("let's finalize the details", 0),
    ("you have a new update", 0),
    ("important: please take action", 1),
    ("we value your input", 0),
    ("urgent: your response is needed", 1),
    ("let's connect soon", 0),
    ("you have a new assignment", 0),
    ("important: please review", 1),
    ("thank you for your cooperation", 0),
    ("urgent: please take note", 1),
    ("let's discuss further", 0),
    ("you have a new reminder", 0),
    ("important: please acknowledge", 1),
    ("we appreciate your feedback", 0),
    ("urgent: please take action", 1),
    ("let's arrange a time to talk", 0),
    ("you have a new message waiting", 0),
    ("important: please check your account", 1),
    ("thank you for your understanding", 0),
    ("urgent: please address this issue", 1),
    ("let's work together on this", 0),
    ("you have a new notification alert", 0),
    ("important: please update your records", 1),
    ("we're here to help you", 0),
    ("urgent: your input is required", 1),
    ("let's schedule a follow-up", 0),
    ("you have a new task to complete", 0),
    ("important: please take note of this", 1),
    ("thank you for your prompt response", 0),
    ("urgent: please review this matter", 1),
    ("let's finalize the arrangements", 0),
    ("you have a new update available", 0),
    ("important: please take action now", 1),
    ("we value your business relationship", 0),
    ("urgent: your attention is crucial", 1),
    ("let's discuss your concerns", 0),
    ("you have a new assignment due", 0),
    ("important: please read this carefully", 1),
    ("thank you for your continued support", 0),
    ("urgent: please respond at your earliest convenience", 1),
    ("let's set up a time to meet", 0),
    ("you have a new task assigned to you", 0),
    ("important: please review the details", 1),
    ("we appreciate your prompt attention", 0),
    ("urgent: please take immediate action", 1),
    ("let's connect to discuss further", 0),
    ("you have a new reminder set", 0),
    ("important: please acknowledge receipt of this message", 1),
    ("thank you for your prompt attention to this matter", 0),
    ("urgent: please address this request", 1),
    ("let's work together to resolve this", 0),
    ("you have a new notification alert set", 0),
    ("important: please update your information promptly", 1),
    ("you've been selected to receive a free cruise.", 1),
    ("just checking in — how's your day going?", 0),
    ("click here to instantly boost your credit score!", 1),
    ("the meeting agenda is attached below.", 0),
    ("get your free trial before it’s gone!", 1),
    ("i'll be out of town this weekend.", 0),
    ("you qualify for debt relief — apply now!", 1),
    ("dinner plans still good for tonight?", 0),
    ("urgent: update your billing info to avoid suspension.", 1),
    ("let’s plan something fun this Friday.", 0),
    ("win $1000 instantly with one click.", 1),
    ("do you want to carpool tomorrow morning?", 0),
    ("try this secret method to lose 20 pounds fast!", 1),
    ("i'll be working remotely on Monday.", 0),
    ("free gift inside just for you!", 1),
    ("did you get my last email?", 0),
    ("increase your income with this side hustle.", 1),
    ("i'll bring dessert for the party.", 0),
    ("lowest insurance rates in your area.", 1),
    ("looking forward to seeing you at the reunion.", 0),
    ("pre-approved for exclusive VIP rewards!", 1),
    ("i uploaded the files to the shared drive.", 0),
    ("don't miss out on this once-in-a-lifetime deal!", 1),
    ("want to join us for game night?", 0),
    ("act now to secure your spot in our rewards program.", 1),
    ("i'll pick you up at 7pm sharp.", 0),
    ("this method helped me retire early.", 1),
    ("thanks for your quick reply!", 0),
    ("click to claim your new iPad!", 1),
    ("let’s sync up before the meeting.", 0),
    ("join our program and start earning today!", 1),
    ("are you bringing your laptop today?", 0),
    ("see how I made $10,000 in a month.", 1),
    ("we should finalize the slides by tonight.", 0),
    ("you’ve earned a surprise reward — open now!", 1),
    ("the forecast looks rainy tomorrow.", 0),
    ("time-sensitive: your invoice is ready to download.", 1),
    ("i'll message you after class.", 0),
    ("save big with this limited offer!", 1),
    ("don’t forget to take out the trash.", 0),
    ("get exclusive access to our investment club.", 1),
    ("can you help me debug this?", 0),
    ("try this trick to pay off your mortgage early!", 1),
    ("thanks again for your support.", 0),
    ("massive discounts available now — act fast!", 1),
    ("let’s go over the assignment together.", 0),
    ("this could change your life forever!", 1),
    ("do you need a ride to campus?", 0),
    ("claim your risk-free bonus today!", 1),
    ("i'll text you when I'm done.", 0),
    ("URGENT: your computer has a virus, click here to fit it.", 1)
]
